return {}
-- return {
--     {
--         "notjedi/nvim-rooter.lua",
--         lazy = false,
--         priority = 1000,
--         config = function()
--             require("nvim-rooter").setup({
--                 update_cwd = true,
--                 update_focused_file = {
--                     enable = true,
--                     update_cwd = true,
--                 },
--             })
--         end,
--     },
-- }
